FROM python:3.10-slim


WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY docker/requirements.api.txt .

RUN pip install --no-cache-dir -r requirements.api.txt

COPY PVPOKE/environment/ .

EXPOSE 8000


CMD ["uvicorn", "mainSocket:app", "--host", "0.0.0.0", "--port", "8000"]